CREATE OR REPLACE VIEW active_products_with_stock AS SELECT p.id, p.name, p.price, i.quantity, i.last_updated FROM product p JOIN inventory i ON p.id = i.product_id WHERE p.is_active = 1

CREATE TABLE audit_log (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, table_name VARCHAR2(50), operation VARCHAR2(10), product_id NUMBER, old_quantity NUMBER, new_quantity NUMBER, timestamp TIMESTAMP DEFAULT SYSDATE)
