-- Oracle-specific initialization script
-- Run this in Oracle to add stored procedure, trigger, view, and audit table

-- Stored procedure to calculate total inventory value
CREATE OR REPLACE PROCEDURE calculate_total_value (total OUT NUMBER) AS
BEGIN
  SELECT NVL(SUM(p.price * i.quantity), 0) INTO total
  FROM product p
  JOIN inventory i ON p.id = i.product_id
  WHERE p.is_active = 1;
END;
/

-- Audit log table
CREATE TABLE audit_log (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR2(50),
  operation VARCHAR2(10),
  product_id NUMBER,
  old_quantity NUMBER,
  new_quantity NUMBER,
  timestamp TIMESTAMP DEFAULT SYSDATE
);

-- Trigger for inventory audit
CREATE OR REPLACE TRIGGER inventory_audit_trigger
AFTER INSERT OR UPDATE ON inventory
FOR EACH ROW
BEGIN
  INSERT INTO audit_log (table_name, operation, product_id, old_quantity, new_quantity, timestamp)
  VALUES ('inventory', CASE WHEN INSERTING THEN 'INSERT' WHEN UPDATING THEN 'UPDATE' END, :NEW.product_id, :OLD.quantity, :NEW.quantity, SYSDATE);
END;
/

-- View for active products with stock
CREATE OR REPLACE VIEW active_products_with_stock AS
SELECT p.id, p.name, p.price, i.quantity, i.last_updated
FROM product p
JOIN inventory i ON p.id = i.product_id
WHERE p.is_active = 1;